### ISSUE TITLE
请问下这个部署在自己服务上有什么需要设置的地方吗

### ISSUE THREAD

**Issue by kanyou** [onewayticket255/UnblockBangumi#1]
我把这个文件部署在了gcp香港服务器上，然后在config.js里面填入了自己的账号和密码，运行了nodejs main.js，但是自己本地只能看港澳台的视频了，国区的不能观看了，请问下还需要什么具体的设置吗，谢谢

**Comment by onewayticket255** [comment]
需要b站大会员帐号
CloudFlare Worker
中国大陆服务器,台湾服务器.
